import { useState } from 'react'
import { Plus, CalendarDays } from 'lucide-react'
import { initialSchedules } from '../services/api'
import Modal from '../components/Modal'
import Toast from '../components/Toast'
export default function Scheduling(){const[data,setData]=useState(initialSchedules);const[modal,setModal]=useState(false);const[toast,setToast]=useState('');const[form,setForm]=useState({day:'Monday',time:'08:00 AM – 10:00 AM',subject:'',room:'',faculty:''})
 function save(e){e.preventDefault();setData(d=>[...d,form]);setModal(false);setToast('Schedule created.')}
 return <div className="page-stack"><div className="page-heading"><div><h1>Academic Schedules</h1><p>Manage class times, rooms, and faculty assignments.</p></div><button className="btn-primary" onClick={()=>setModal(true)}><Plus size={17}/> Add Schedule</button></div><section className="panel"><div className="panel-heading"><h2><CalendarDays size={18}/> Class schedule</h2><span>First Semester AY 2026–2027</span></div><div className="schedule-list">{data.map((s,i)=><div className="schedule-row" key={i}><div className="schedule-day">{s.day.slice(0,3)}</div><div className="schedule-details"><strong>{s.subject}</strong><p>{s.faculty} · {s.room}</p></div><span className="schedule-time">{s.time}</span></div>)}</div></section>{modal&&<Modal title="Add Class Schedule" onClose={()=>setModal(false)}><form className="modal-form" onSubmit={save}><label>Day<select value={form.day} onChange={e=>setForm({...form,day:e.target.value})}>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(x=><option>{x}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Time<input required value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Room<input required value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/></label><label>Faculty<input required value={form.faculty} onChange={e=>setForm({...form,faculty:e.target.value})}/></label><div className="modal-actions"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn-primary">Save Schedule</button></div></form></Modal>}<Toast message={toast} onClose={()=>setToast('')}/></div>
}
